# -*- coding: utf-8 -*-
"""langchain-chroma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZC2aiMGuziVWcxVcS-l86_ovPB8D9vB
"""

import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = "Your Api Key"

!pip install langchain chromadb tiktoken pypdf \
langchain-community langchain-huggingface \
transformers sentence-transformers huggingface_hub

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_core.documents import Document

  # Create LangChain documents for IPL players

doc1 = Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
doc2 = Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    )
doc3 = Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    )
doc4 = Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    )
doc5 = Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )

docs = [doc1,doc2,doc3,doc4,doc5]

vector_store = Chroma(
    collection_name="sample",
    embedding_function=HuggingFaceEmbeddings(),
    persist_directory="chroma_db"
)

# add documents
vector_store.add_documents(docs)

# view documents
vector_store.get(include=["embeddings","documents","metadatas"])

# search documents
vector_store.similarity_search(
    query="Who amoung these are a bowler?",
    k=2
)

# search with similarity score
vector_store.similarity_search_with_score(
    query="Who amoung these are a bowler?",
    k=2
)

# meta-data filtering
vector_store.similarity_search(
    query="",
    k=2,
    filter={"team":"Mumbai Indians"}
)

# update documents
updated_doc1 = Document(
    page_content="Virat Kohli, the former captain of Royal Challengers Bangalore (RCB), is renowned for his aggressive leadership and consistent batting performances. He holds the record for the most runs in IPL history, including multiple centuries in a single season. Despite RCB not winning an IPL title under his captaincy, Kohli's passion and fitness set a benchmark for the league. His ability to chase targets and anchor innings has made him one of the most dependable players in T20 cricket.",
    metadata={"team": "Royal Challengers Bangalore"}
)

vector_store.update_document(document_id='53a3796d-fc83-45bb-a93f-aaf78fad555e', document=updated_doc1)

# view documents
vector_store.get(include=["embeddings","documents","metadatas"])

# delete document
vector_store.delete(ids='53a3796d-fc83-45bb-a93f-aaf78fad555e')

# view documents
vector_store.get(include=["embeddings","documents","metadatas"])

