# -*- coding: utf-8 -*-
"""langchain_chainproblem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pH6ar1cYjYgGTUzwdUof3_XTVLORizgD
"""

import random

class NakliLLM:
  def __init__(self):
    print('LLM creared')

  def predict(self, prompt):

    response_list = [
        'Delhi is the capital of India',
        'IPL is a cricket league',
        'AI stands for Artificial Intelligence'
    ]

    return {'response': random.choice(response_list)}

llm = NakliLLM()

llm.predict('what is the capital of india')

class NakliPropmtTemplate:

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def format(self, input_dict):
    return self.template.format(**input_dict)

template = NakliPropmtTemplate(
    template = 'Wrire a {length} poem about {topic}',
    input_variables = ['length','topic']
)

prompt = template.format({'length':'short','topic': 'india'})

llm =NakliLLM()

llm.predict(prompt)

class NakliLLMChain:

  def __init__(self, llm, prompt):
    self.llm = llm
    self.prompt = prompt

  def run(self, input_dict):
    final_prompt = self.prompt.format(input_dict)
    result=self.llm.predict(final_prompt)

    return result['response']

template = NakliPropmtTemplate(
    template = 'Wrire a {length} poem about {topic}',
    input_variables = ['length','topic']
)

llm = NakliLLM()

chain = NakliLLMChain(llm, template)

chain.run({'length':'short','topic':'india'})

