# -*- coding: utf-8 -*-
"""langchain_runnables_consept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grkJWxZsySi8DrkzY8dr239nE_ip3N6E
"""

from abc import ABC, abstractmethod

class Runnable(ABC):

  @abstractmethod
  def invoke(input_data):
    pass

import random

class NakliLLM(Runnable):
  def __init__(self):
    print('LLM creared')

  def invoke(self,prompt):
    response_list = [
        'Delhi is the capital of India',
        'IPL is a cricket league',
        'AI stands for Artificial Intelligence'
    ]

    return {'response': random.choice(response_list)}

  def predict(self, prompt):

    response_list = [
        'Delhi is the capital of India',
        'IPL is a cricket league',
        'AI stands for Artificial Intelligence'
    ]

    return {'response': random.choice(response_list)}

class NakliStrOutputParser(Runnable):

  def __init__(self):
    pass

  def invoke(self,input_data):
     return input_data['response']

class RunnableConnector(Runnable):

    def __init__(self, runnable_list):
        self.runnable_list = runnable_list

    def invoke(self, input_data):

        for runnable in self.runnable_list:
            input_data = runnable.invoke(input_data)

        return input_data

class NakliPropmtTemplate(Runnable):

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def invoke(self, input_dict):
    return self.template.format(**input_dict)

  def format(self, input_dict):
    return self.template.format(**input_dict)

template = NakliPropmtTemplate(
    template = 'Wrire a {length} poem about {topic}',
    input_variables = ['length','topic']
)

llm = NakliLLM()

parser = NakliStrOutputParser()

chain = RunnableConnector([template, llm,parser])

chain.invoke({'length':'small','topic':'india'})

template1 = NakliPropmtTemplate(
    template = 'Wrire a joke about {topic}',
    input_variables = ['topic']
)

template2 = NakliPropmtTemplate(
    template = 'Explain the following joke {response}',
    input_variables = ['response']
)

llm = NakliLLM()

parser = NakliStrOutputParser()

chain1 = RunnableConnector([template1, llm])

chain2 = RunnableConnector([template2, llm,parser])

final_chain = RunnableConnector([chain1,chain2])

final_chain.invoke({'topic':'cricket'})

